<script setup lang="ts">
import { nextTick, reactive, ref } from 'vue'
import type { CreateTripInput } from '@/api/types'
const props=defineProps<{busy?:boolean;initial?:CreateTripInput;fieldErrors?:Record<string,string>}>(),emit=defineEmits<{submit:[value:CreateTripInput]}>()
const today=new Date().toISOString().slice(0,10),error=ref('')
const form=reactive(props.initial??{destination:'',startDate:today,days:3,budget:{amount:'5000.00',currency:'CNY'},travelers:1,preferences:[],timezone:'Asia/Shanghai',additionalRequirements:''})
const preferences=ref(form.preferences.join('，'))
function fail(field:string,message:string){error.value=message;void nextTick(()=>(document.getElementById(field) as HTMLElement|null)?.focus());return false}
function positiveMoney(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value))return false;const [whole,fraction='']=value.split('.');return BigInt(whole!)*100n+BigInt(fraction.padEnd(2,'0'))>0n}
function validTimezone(value:string){try{new Intl.DateTimeFormat('zh-CN',{timeZone:value}).format();return true}catch{return false}}
function submit(){const destination=form.destination.trim(),tags=preferences.value.split(/[，,]/).map(x=>x.trim()).filter(Boolean);if(!destination)return fail('destination','目的地不能为空');if(form.days<1||form.days>30)return fail('days','出行天数应为 1–30 天');if(!positiveMoney(form.budget.amount))return fail('budget','请输入有效预算金额');if(form.travelers<1||form.travelers>50)return fail('travelers','出行人数应为 1–50 人');if(form.startDate<today)return fail('startDate','开始日期不能早于今天');if(!validTimezone(form.timezone))return fail('timezone','请输入有效 IANA 时区');if(tags.length>20||tags.some(x=>x.length>50))return fail('preferences','偏好最多 20 项，每项不超过 50 字');error.value='';emit('submit',{...form,destination,preferences:tags})}
</script>
<template><form class="form-grid" @submit.prevent="submit"><label class="span-2">目的地<input id="destination" v-model="form.destination" :aria-invalid="!!fieldErrors?.destination" aria-describedby="destination-error" required maxlength="200" placeholder="例如：京都"><small v-if="fieldErrors?.destination" id="destination-error" class="form-error">{{fieldErrors.destination}}</small></label><label>开始日期<input id="startDate" v-model="form.startDate" type="date" :min="today" :aria-invalid="!!fieldErrors?.startDate" aria-describedby="startDate-error" required><small v-if="fieldErrors?.startDate" id="startDate-error" class="form-error">{{fieldErrors.startDate}}</small></label><label>出行天数<input id="days" v-model.number="form.days" type="number" min="1" max="30" :aria-invalid="!!fieldErrors?.days" aria-describedby="days-error" required><small v-if="fieldErrors?.days" id="days-error" class="form-error">{{fieldErrors.days}}</small></label><label>团队总预算<input id="budget" v-model.trim="form.budget.amount" inputmode="decimal" :aria-invalid="!!fieldErrors?.budget" aria-describedby="budget-error" required><small v-if="fieldErrors?.budget" id="budget-error" class="form-error">{{fieldErrors.budget}}</small></label><label>币种<select v-model="form.budget.currency"><option>CNY</option><option>USD</option><option>JPY</option><option>EUR</option></select></label><label>出行人数<input id="travelers" v-model.number="form.travelers" type="number" min="1" max="50" :aria-invalid="!!fieldErrors?.travelers" aria-describedby="travelers-error" required><small v-if="fieldErrors?.travelers" id="travelers-error" class="form-error">{{fieldErrors.travelers}}</small></label><label>时区<input id="timezone" v-model.trim="form.timezone" :aria-invalid="!!fieldErrors?.timezone" aria-describedby="timezone-error" required placeholder="Asia/Shanghai"><small v-if="fieldErrors?.timezone" id="timezone-error" class="form-error">{{fieldErrors.timezone}}</small></label><label class="span-2">旅行偏好（逗号分隔）<input id="preferences" v-model="preferences" maxlength="1020" :aria-invalid="!!fieldErrors?.preferences" aria-describedby="preferences-error" placeholder="美食，历史，轻松"><small v-if="fieldErrors?.preferences" id="preferences-error" class="form-error">{{fieldErrors.preferences}}</small></label><label class="span-2">补充要求<textarea id="additionalRequirements" v-model="form.additionalRequirements" maxlength="2000" rows="4" :aria-invalid="!!fieldErrors?.additionalRequirements" aria-describedby="additionalRequirements-error" placeholder="例如：避免太早出发，希望安排素食餐厅"></textarea><small v-if="fieldErrors?.additionalRequirements" id="additionalRequirements-error" class="form-error">{{fieldErrors.additionalRequirements}}</small></label><p v-if="error" class="form-error span-2" role="alert">{{error}}</p><div class="span-2 actions"><button :disabled="busy">{{busy?'正在提交…':'生成我的行程'}}</button></div></form></template>
