package com.travelassistant.trip.ai;
import com.travelassistant.common.exception.BusinessException; import java.util.*; import java.util.concurrent.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service;
@Service
public class TripPlanningGateway {
 private final TripPlanningProvider provider; private final TripPlanningProperties properties; private final TripPlanValidator validator; private final Semaphore global;
 private final ExecutorService calls=Executors.newVirtualThreadPerTaskExecutor();
 private final ConcurrentHashMap<String,Deque<Long>> userRequests=new ConcurrentHashMap<>();
 public TripPlanningGateway(TripPlanningProvider provider,TripPlanningProperties properties,TripPlanValidator validator){this.provider=provider;this.properties=properties;this.validator=validator;global=new Semaphore(properties.globalConcurrency());}
 public void admit(String userId){enforceUserRate(userId);}
 public TripPlan generate(String userId,TripPlanningRequest request){if(!global.tryAcquire())throw new BusinessException("RATE_LIMITED","生成并发已达上限",HttpStatus.TOO_MANY_REQUESTS);long deadline=System.nanoTime()+properties.totalTimeout().toNanos();
  try {TripPlanningException last=null; for(int attempt=1;attempt<=properties.maxAttempts();attempt++){if(System.nanoTime()>=deadline)throw new TripPlanningException("AI_TIMEOUT","AI 生成超过总截止时间",false);try{TripPlan plan=callWithinDeadline(request,deadline);validator.validate(request,plan);return plan;}catch(TripPlanningException e){last=e;if(!e.isRetryable()||attempt==properties.maxAttempts()||System.nanoTime()>=deadline)throw e; backoff(attempt,deadline);}} throw last;
  } finally {global.release();}}
 private void enforceUserRate(String userId){long now=System.currentTimeMillis(),cutoff=now-60_000;Deque<Long> q=userRequests.computeIfAbsent(userId,k->new ArrayDeque<>());synchronized(q){while(!q.isEmpty()&&q.peekFirst()<cutoff)q.removeFirst();if(q.size()>=properties.userRequestsPerMinute())throw new BusinessException("RATE_LIMITED","请求过于频繁",HttpStatus.TOO_MANY_REQUESTS);q.addLast(now);}}
 private void backoff(int attempt,long deadline){try{long delay=Math.min(1000,100L*(1L<<(attempt-1)))+ThreadLocalRandom.current().nextLong(50);long remaining=TimeUnit.NANOSECONDS.toMillis(Math.max(0,deadline-System.nanoTime()));if(remaining<=0)throw new TripPlanningException("AI_TIMEOUT","AI 生成超过总截止时间",false);Thread.sleep(Math.min(delay,remaining));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new TripPlanningException("AI_UNAVAILABLE","生成任务被中断",false);}}
 private TripPlan callWithinDeadline(TripPlanningRequest request,long deadline){long remaining=deadline-System.nanoTime();if(remaining<=0)throw new TripPlanningException("AI_TIMEOUT","AI 生成超过总截止时间",false);Future<TripPlan> future=calls.submit(()->provider.generate(request));try{return future.get(remaining,TimeUnit.NANOSECONDS);}catch(TimeoutException e){future.cancel(true);throw new TripPlanningException("AI_TIMEOUT","AI 生成超过总截止时间",false);}catch(InterruptedException e){future.cancel(true);Thread.currentThread().interrupt();throw new TripPlanningException("AI_UNAVAILABLE","生成任务被中断",false);}catch(ExecutionException e){Throwable cause=e.getCause();if(cause instanceof TripPlanningException planning)throw planning;if(cause instanceof RuntimeException runtime)throw runtime;throw new TripPlanningException("AI_UNAVAILABLE","AI 服务调用失败",true);}}
 public String providerName(){return provider.providerName();} public String modelName(){return provider.modelName();} public String promptVersion(){return properties.promptVersion();}
}
