package com.travelassistant.consultation;
import com.travelassistant.common.api.*;import com.travelassistant.common.web.RequestIdFilter;import com.travelassistant.consultation.api.ConsultationDtos.*;import jakarta.servlet.http.*;import jakarta.validation.constraints.*;import java.security.Principal;import java.util.List;import org.springframework.http.*;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
@Validated @RestController @RequestMapping("/api/v1/conversations")public class ConversationController{private final ConversationService service;private final ConversationQueryService queries;private final ConversationStreamService streaming;public ConversationController(ConversationService s,ConversationQueryService q,ConversationStreamService stream){service=s;queries=q;streaming=stream;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED)ApiResponse<ConversationView>create(Principal p,@RequestBody CreateConversationRequest body,HttpServletRequest r){return ApiResponse.of(service.create(p.getName(),body.title(),body.tripId()),id(r));}
 @GetMapping PagedResponse<ConversationSummary>list(Principal p,@RequestParam(required=false)String cursor,@RequestParam(defaultValue="20")@Min(1)@Max(100)int limit,HttpServletRequest r){PageResult<ConversationSummary>page=queries.list(p.getName(),cursor,limit);return new PagedResponse<>(page.items(),new PageMeta(id(r),page.nextCursor(),page.hasMore()));}
 @GetMapping("/{conversationId}")ApiResponse<ConversationView>get(Principal p,@PathVariable String conversationId,HttpServletRequest r){return ApiResponse.of(service.get(p.getName(),conversationId),id(r));}
 @GetMapping("/{conversationId}/messages")PagedResponse<MessageView>messages(Principal p,@PathVariable String conversationId,@RequestParam(required=false)String cursor,@RequestParam(defaultValue="50")@Min(1)@Max(100)int limit,HttpServletRequest r){PageResult<MessageView>page=queries.messages(p.getName(),conversationId,cursor,limit);return new PagedResponse<>(page.items(),new PageMeta(id(r),page.nextCursor(),page.hasMore()));}
 @PostMapping("/{conversationId}/messages")ResponseEntity<ApiResponse<TurnView>>ask(Principal p,@PathVariable String conversationId,@RequestHeader("Idempotency-Key")@Size(min=8,max=128)String key,@RequestBody SendMessageRequest body,HttpServletRequest r){TurnView turn=service.ask(p.getName(),conversationId,key,body.content());return ResponseEntity.status(turn.replayed()?HttpStatus.OK:HttpStatus.CREATED).body(ApiResponse.of(turn,id(r)));}
 @PostMapping(value="/{conversationId}/messages:stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE)SseEmitter stream(Principal p,@PathVariable String conversationId,@RequestHeader("Idempotency-Key")@Size(min=8,max=128)String key,@RequestBody SendMessageRequest body,HttpServletResponse response){streamHeaders(response);return streaming.start(p.getName(),conversationId,key,body.content());}
 @GetMapping(value="/{conversationId}/streams/{streamId}",produces=MediaType.TEXT_EVENT_STREAM_VALUE)SseEmitter replay(Principal p,@PathVariable String conversationId,@PathVariable String streamId,@RequestHeader(value="Last-Event-ID",defaultValue="0")@Min(0)int after,HttpServletResponse response){streamHeaders(response);return streaming.replay(p.getName(),conversationId,streamId,after);}
 @DeleteMapping("/{conversationId}/streams/{streamId}")@ResponseStatus(HttpStatus.NO_CONTENT)void cancel(Principal p,@PathVariable String conversationId,@PathVariable String streamId){streaming.cancel(p.getName(),conversationId,streamId);}private void streamHeaders(HttpServletResponse response){response.setHeader(HttpHeaders.CACHE_CONTROL,"no-cache, no-store");response.setHeader("X-Accel-Buffering","no");}private String id(HttpServletRequest r){return(String)r.getAttribute(RequestIdFilter.ATTRIBUTE);}record PagedResponse<T>(List<T>data,PageMeta meta){}record PageMeta(String requestId,String nextCursor,boolean hasMore){}}
