package com.travelassistant.trip;

import com.travelassistant.common.exception.BusinessException; import com.travelassistant.trip.ai.TripPlan; import com.travelassistant.trip.ai.TripPlanningGateway; import com.travelassistant.trip.api.CreateTripRequest; import com.travelassistant.user.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import tools.jackson.databind.ObjectMapper;
@Service public class TripCommandService {
 private static final Set<GenerationJobStatus> ACTIVE=Set.of(GenerationJobStatus.QUEUED,GenerationJobStatus.RUNNING);
 private final TripRepository trips;private final TripGenerationJobRepository jobs;private final IdempotencyRecordRepository idempotency;private final UserRepository users;private final TripVersionRepository versions;private final TripVersionRestoreRepository restores;private final TripRequestNormalizer normalizer;private final TripPlanMapper planMapper;private final ObjectMapper mapper;private final Clock clock;private final ApplicationEventPublisher events;private final TripPlanningGateway planning;private final TripDispatchCapacity capacity;
 public TripCommandService(TripRepository t,TripGenerationJobRepository j,IdempotencyRecordRepository i,UserRepository u,TripVersionRepository v,TripVersionRestoreRepository r,TripRequestNormalizer n,TripPlanMapper pm,ObjectMapper m,Clock c,ApplicationEventPublisher e,TripPlanningGateway p,TripDispatchCapacity cap){trips=t;jobs=j;idempotency=i;users=u;versions=v;restores=r;normalizer=n;planMapper=pm;mapper=m;clock=c;events=e;planning=p;capacity=cap;}
 @Transactional public Trip create(String userId,String key,CreateTripRequest request){var n=normalizer.normalize(request);String snapshot=normalizer.json(n),hash=hash(snapshot);User user=users.findLockedById(userId).orElseThrow(()->unauthorized());var existing=idempotency.findByUserIdAndOperationAndKey(userId,"CREATE_TRIP",key);
  if(existing.isPresent()){var record=existing.get();if(record.getExpiresAt().isAfter(clock.instant())){if(!record.getRequestHash().equals(hash))throw conflict("IDEMPOTENCY_KEY_CONFLICT","幂等键已用于其他请求");return owned(record.getResourceId(),userId);}idempotency.delete(record);idempotency.flush();}
  admit(userId);Trip trip=trips.saveAndFlush(new Trip(user,n.destination(),n.startDate(),n.days(),n.travelers(),n.budget(),n.currency(),n.timezone(),json(n.preferences()),n.additionalRequirements()));
  TripGenerationJob job=jobs.save(new TripGenerationJob(trip,null,GenerationType.INITIAL,null,json(normalizer.planning(n,null,null))));
  try{idempotency.saveAndFlush(new IdempotencyRecord(user,"CREATE_TRIP",key,hash,trip.getId(),clock.instant().plus(Duration.ofHours(24))));}catch(DataIntegrityViolationException e){throw conflict("IDEMPOTENCY_KEY_CONFLICT","幂等键冲突");}
  events.publishEvent(new TripGenerationRequested(job.getId()));return trip;
 }
 @Transactional public Trip adjust(String userId,String tripId,String instruction){Trip trip=lockOwned(tripId,userId);if(trip.getCurrentVersion()==null)throw conflict("TRIP_STATE_CONFLICT","当前没有可调整版本");ensureIdle(tripId);admit(userId);TripPlan base=planMapper.fromVersion(trip.getCurrentVersion());var n=fromTrip(trip);TripGenerationJob job=jobs.save(new TripGenerationJob(trip,trip.getCurrentVersion(),GenerationType.ADJUSTMENT,instruction.trim(),json(normalizer.planning(n,instruction.trim(),base))));events.publishEvent(new TripGenerationRequested(job.getId()));return trip;}
 @Transactional public Trip update(String userId,String tripId,CreateTripRequest request){Trip trip=lockOwned(tripId,userId);ensureIdle(tripId);admit(userId);var n=normalizer.normalize(request);trip.replaceRequirements(n.destination(),n.startDate(),n.days(),n.travelers(),n.budget(),n.currency(),n.timezone(),json(n.preferences()),n.additionalRequirements());trip.beginGeneration();TripGenerationJob job=jobs.save(new TripGenerationJob(trip,trip.getCurrentVersion(),GenerationType.REPLAN,null,json(normalizer.planning(n,null,trip.getCurrentVersion()==null?null:planMapper.fromVersion(trip.getCurrentVersion())))));events.publishEvent(new TripGenerationRequested(job.getId()));return trip;}
 @Transactional public void delete(String userId,String tripId){Trip trip=trips.findByIdAndUserId(tripId,userId).orElse(null);if(trip!=null){trip.softDelete();return;}if(!trips.findOwnerIncludingDeleted(tripId).filter(userId::equals).isPresent())throw notFound();}
 @Transactional public Trip restore(String userId,String tripId,int number){Trip trip=lockOwned(tripId,userId);ensureIdle(tripId);TripVersion target=versions.findByTripIdAndVersionNumber(tripId,number).orElseThrow(()->notFound());TripVersion from=trip.getCurrentVersion();trip.publish(target);restores.save(new TripVersionRestore(trip,from,target,trip.getUser()));return trip;}
 private TripRequestNormalizer.Normalized fromTrip(Trip t){try{String value=t.getPreferencesJson();for(int i=0;i<3;i++){var node=mapper.readTree(value);if(!node.isString())break;value=node.asText();}return new TripRequestNormalizer.Normalized(t.getDestination(),t.getStartDate(),t.getDays(),t.getTravelers(),t.getBudgetAmount(),t.getCurrency(),t.getTimezone(),mapper.readValue(value,mapper.getTypeFactory().constructCollectionType(List.class,String.class)),t.getAdditionalRequirements());}catch(Exception e){throw new IllegalStateException(e);}}
 private void ensureIdle(String id){if(jobs.existsByTripIdAndStatusIn(id,ACTIVE))throw conflict("TRIP_STATE_CONFLICT","已有生成任务进行中");} private void admit(String userId){planning.admit(userId);capacity.reserveForCurrentTransaction();}
 private Trip lockOwned(String id,String user){return trips.lockOwned(id,user).orElseThrow(()->notFound());} private Trip owned(String id,String user){return trips.findByIdAndUserId(id,user).orElseThrow(()->notFound());}
 private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private BusinessException conflict(String c,String m){return new BusinessException(c,m,HttpStatus.CONFLICT);} private BusinessException notFound(){return new BusinessException("TRIP_NOT_FOUND","行程不存在",HttpStatus.NOT_FOUND);} private BusinessException unauthorized(){return new BusinessException("UNAUTHORIZED","需要有效身份认证",HttpStatus.UNAUTHORIZED);}
}
