package com.travelassistant.trip;
import com.travelassistant.trip.api.TripDtos.*; import com.travelassistant.realtime.RealtimeService; import java.math.*; import java.util.*; import org.springframework.stereotype.Component; import tools.jackson.databind.ObjectMapper;
@Component public class TripResponseMapper {
 private final ObjectMapper mapper; private final RealtimeService realtime; public TripResponseMapper(ObjectMapper m,RealtimeService r){mapper=m;realtime=r;}
 public TripView trip(Trip t){TripVersion v=t.getCurrentVersion();List<DayView> days=v==null?List.of():days(v);List<String>warnings=v==null?List.of():strings(v.getWarningsJson());BudgetBreakdown breakdown=v==null?null:budget(v);return new TripView(t.getId(),t.getDestination(),t.getStartDate().toString(),t.getDays(),t.getTravelers(),money(t.getBudgetAmount(),t.getCurrency()),v==null?null:money(v.getEstimatedTotal(),v.getCurrency()),t.getCurrency(),t.getTimezone(),strings(t.getPreferencesJson()),t.getAdditionalRequirements(),t.getStatus(),v==null?null:v.getVersionNumber(),t.getFailureCode(),warnings,breakdown,days,t.getCreatedAt().toString(),t.getDestinationLocation()==null?null:realtime.view(t.getDestinationLocation()));}
 public TripSummary summary(Trip t){return new TripSummary(t.getId(),t.getDestination(),t.getStartDate().toString(),t.getDays(),t.getStatus(),t.getCurrentVersion()==null?null:t.getCurrentVersion().getVersionNumber(),t.getFailureCode(),t.getCreatedAt().toString());}
 public VersionSummary versionSummary(TripVersion v){return new VersionSummary(v.getVersionNumber(),money(v.getEstimatedTotal(),v.getCurrency()),v.getCreatedAt().toString());}
 public VersionView version(TripVersion v){return new VersionView(v.getVersionNumber(),money(v.getEstimatedTotal(),v.getCurrency()),strings(v.getWarningsJson()),budget(v),days(v),v.getCreatedAt().toString());}
 private List<DayView> days(TripVersion v){return v.getItineraryDays().stream().map(d->new DayView(d.getDayNumber(),d.getDate().toString(),d.getSummary(),d.getActivities().stream().map(a->new ActivityView(a.getSequenceNumber(),a.getStartTime().toString(),a.getEndTime().toString(),a.getTitle(),a.getLocation(),a.getDescription(),money(a.getEstimatedCost(),a.getCurrency()),a.getCategory(),a.getTransportAdvice())).toList())).toList();}
 private BudgetBreakdown budget(TripVersion v){EnumMap<BudgetCategory,BigDecimal> sums=new EnumMap<>(BudgetCategory.class);for(BudgetCategory c:BudgetCategory.values())sums.put(c,BigDecimal.ZERO);v.getItineraryDays().forEach(d->d.getActivities().forEach(a->sums.merge(a.getCategory(),a.getEstimatedCost(),BigDecimal::add)));List<CategoryAmount> categories=Arrays.stream(BudgetCategory.values()).map(c->new CategoryAmount(c,money(sums.get(c),v.getCurrency()))).toList();BigDecimal budget=v.getBudgetAmount(),total=v.getEstimatedTotal();boolean over=total.compareTo(budget)>0;return new BudgetBreakdown(categories,money(total,v.getCurrency()),over,over?money(total.subtract(budget),v.getCurrency()):null);}
 private Money money(BigDecimal value,String currency){return new Money(value.setScale(2,RoundingMode.HALF_UP).toPlainString(),currency);} private List<String> strings(String json){try{String value=json;for(int i=0;i<3;i++){var node=mapper.readTree(value);if(!node.isString())break;value=node.asText();}return mapper.readValue(value,mapper.getTypeFactory().constructCollectionType(List.class,String.class));}catch(Exception e){return List.of();}}
}
